# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run

jobs:
  build:
    docker:
      - image: jdoi/json-dir_elm-dev:latest
    steps:
      - checkout
      - run: |
          cd app
          yarn build
      - store_artifacts:
          path: app/dist
      - persist_to_workspace:
          root: app
          paths:
            - dist
  deploy:
    docker:
      - image: andreysenov/firebase-tools:latest
    steps:
      - checkout
      - attach_workspace:

          at: app/dist
      - run: |
          cd app
          ls dist
          firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2

  btd:
    jobs:
      - build
      - deploy:
          requires:
            - build

